### ISSUE TITLE
Cannot compile with wxwidgets 3.2

### ISSUE THREAD

**Issue by bartlibert** [solemnwarning/rehex#178]
If I try to compile the latest master, I get the following error:

```src/CommentTree.cpp:24:10: fatal error: gtk/gtk.h: No such file or directory
   24 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
```
I found the reason is that the correct gtk flags are not used, because on my system I have wxwidgets-gtk3 v3.2.0

The reason it fails is that the makefile uses the gtk-config tool to get the correct `GTK_CFLAGS` and `GTK_LIBS`

However, if the following check fails, this tools is a no-op:
```
#if defined(__WXGTK__) && !wxCHECK_VERSION(3,1,3)
```
Now in my case, __WXGTK__ is defined, but the wx version is 3.2.0. to this tool does nothing, so the GTK_* variables are empty.
If I remove the wxCHECK_VERSION part, everything works, but that's probably not the correct way to fix it ;)

**Comment by solemnwarning** [comment]
uhhh... actually removing the version check from `gtk-config.cpp` looks like exactly the right thing to do, thanks for pointing that out xD

Context: I was originally only linking directly against GTK for a hack that was no longer necessary after wxWidgets 3.1.3, but 69a4b114538b10456ec352a681d5700c7fb56b6b adds another hack that always needs it.
